api_version = "2026-04"

[[extensions]]
uid = "e06e29ce-d27d-24d0-739c-146523309c0a826e69c9"
type = "ui_extension"
name = "Point MAN Account Points"
handle = "pointman-account-points"

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.profile.block.render"

[extensions.capabilities]
api_access = true
