api_version = "2025-10"

[[extensions]]
uid = "e06e29ce-d27d-24d0-739c-146523309c0a826e69c9"
type = "ui_extension"
name = "Point MAN Account Points"
handle = "pointman-account-points"

[[extensions.targeting]]
module = "./src/ProfileBlockExtension.jsx"
target = "customer-account.profile.block.render"

[extensions.capabilities]
api_access = true
network_access = true
