# extensions/pointman-account-render-test/shopify.extension.toml
api_version = "2026-04"

[[extensions]]
name = "pointman-account-render-test"
handle = "pointman-account-render-test"
type = "ui_extension"
uid = "69e70299-7be8-99c1-b658-ef1d29f39f6fc2be0c91"

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.profile.block.render"

[extensions.capabilities]
api_access = true
