# extensions/pointman-editor-collection/shopify.extension.toml
api_version = "2025-10"

[[extensions]]
name = "Point MAN"
type = "editor_extension_collection"
handle = "pointman-editor-collection"
includes = [
  "pointman-account-points",
  "pointman-account-history",
  "pointman-account-render-test"
]
